import AOSProvider from "@/Provider/AOSProvider/AOSProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import { NavigationEvents } from "@/Provider/navigation-events/navigation-events";
import { Suspense } from "react";
import Loading from "./loading";
import ContextProvider from "@/Context/ContextProvider";
import ReduxProvider from "@/Redux/ReduxProvider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  //use this to set the title and description of the page in the head tag of the html document
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
      </head>
      <body className={`${inter.className} relative`}>
        <ReduxProvider>
          <AOSProvider>
            <NavigationEvents>
              <Suspense fallback={<Loading />}>
                <ContextProvider>{children}</ContextProvider>
              </Suspense>
            </NavigationEvents>
          </AOSProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
